def on_forever():
    if pins.analog_read_pin(AnalogPin.P1) > 130:
        led.plot(0, 0)
        led.plot(0, 1)
        led.plot(0, 2)
        led.plot(0, 3)
        led.plot(0, 4)
        pins.analog_write_pin(AnalogPin.P15, 1023)
        pins.analog_write_pin(AnalogPin.P16, 0)
    elif pins.analog_read_pin(AnalogPin.P1) > 120:
        led.plot(0, 0)
        led.plot(0, 1)
        led.plot(0, 2)
        led.plot(0, 3)
        led.unplot(0, 4)
        pins.analog_write_pin(AnalogPin.P15, 1023)
        pins.analog_write_pin(AnalogPin.P16, 0)
    elif pins.analog_read_pin(AnalogPin.P1) > 110:
        led.plot(0, 0)
        led.plot(0, 1)
        led.plot(0, 2)
        led.unplot(0, 3)
        led.unplot(0, 4)
        pins.analog_write_pin(AnalogPin.P15, 1023)
        pins.analog_write_pin(AnalogPin.P16, 0)
    elif pins.analog_read_pin(AnalogPin.P1) > 100:
        led.plot(0, 0)
        led.plot(0, 1)
        led.unplot(0, 2)
        led.unplot(0, 3)
        led.unplot(0, 4)
        pins.analog_write_pin(AnalogPin.P15, 1023)
        pins.analog_write_pin(AnalogPin.P16, 0)
    elif pins.analog_read_pin(AnalogPin.P1) > 90:
        led.plot(0, 0)
        led.unplot(0, 1)
        led.unplot(0, 2)
        led.unplot(0, 3)
        led.unplot(0, 4)
        pins.analog_write_pin(AnalogPin.P15, 1023)
        pins.analog_write_pin(AnalogPin.P16, 0)
    else:
        pins.analog_write_pin(AnalogPin.P15, 0)
        pins.analog_write_pin(AnalogPin.P16, 0)
        led.unplot(0, 0)
        led.unplot(0, 1)
        led.unplot(0, 2)
        led.unplot(0, 3)
        led.unplot(0, 4)
    if pins.analog_read_pin(AnalogPin.P2) > 90:
        led.plot(4, 0)
        led.plot(4, 1)
        led.plot(4, 2)
        led.plot(4, 3)
        led.plot(4, 4)
        pins.analog_write_pin(AnalogPin.P13, 1023)
        pins.analog_write_pin(AnalogPin.P14, 0)
    elif pins.analog_read_pin(AnalogPin.P2) > 80:
        led.plot(4, 0)
        led.plot(4, 1)
        led.plot(4, 2)
        led.plot(4, 3)
        led.unplot(4, 4)
        pins.analog_write_pin(AnalogPin.P13, 1023)
        pins.analog_write_pin(AnalogPin.P14, 0)
    elif pins.analog_read_pin(AnalogPin.P2) > 70:
        led.plot(4, 0)
        led.plot(4, 1)
        led.plot(4, 2)
        led.unplot(4, 3)
        led.unplot(4, 4)
        pins.analog_write_pin(AnalogPin.P13, 1023)
        pins.analog_write_pin(AnalogPin.P14, 0)
    elif pins.analog_read_pin(AnalogPin.P2) > 60:
        led.plot(4, 0)
        led.plot(4, 1)
        led.unplot(4, 2)
        led.unplot(4, 3)
        led.unplot(4, 4)
        pins.analog_write_pin(AnalogPin.P13, 1023)
        pins.analog_write_pin(AnalogPin.P14, 0)
    elif pins.analog_read_pin(AnalogPin.P2) > 50:
        led.plot(4, 0)
        led.unplot(4, 1)
        led.unplot(4, 2)
        led.unplot(4, 3)
        led.unplot(4, 4)
        pins.analog_write_pin(AnalogPin.P13, 1023)
        pins.analog_write_pin(AnalogPin.P14, 0)
    else:
        led.unplot(4, 0)
        led.unplot(4, 1)
        led.unplot(4, 2)
        led.unplot(4, 3)
        led.unplot(4, 4)
        pins.analog_write_pin(AnalogPin.P13, 0)
        pins.analog_write_pin(AnalogPin.P14, 0)
    basic.pause(100)
basic.forever(on_forever)
